#!/bin/bash
#DrTM Script for CLouldLab

yes | sudo apt-get update
yes | sudo apt-get install build-essential
yes | sudo apt-get install libibverbs-dev
yes | sudo apt install util-linux
yes | sudo apt-get install libzmq3-dev
yes | sudo git clone https://github.com/SJTU-IPADS/SSMalloc.git
cd SSMalloc/
sudo make 
sudo make install 
cd 
yes | sudo apt-get install ptpd
sudo service start ptpd
sudo apt-get install -y librdmacm-dev
sudo apt-get install -y libpci-dev
sudo apt-get install -y libibumad-dev
sudo apt-get install -y libboost-system-dev
cd /usr/include
yes | sudo git clone https://github.com/zeromq/cppzmq.git 
sudo cp cppzmq/zmq.hpp /usr/include
cd 
#yes | sudo git clone https://github.com/SJTU-IPADS/drtm.git
cd drtm/
ifconfig
#cd drtm/microbench/rdma/
#Modify drtm/microbench/rdma/network_node.h to use correct ip addresses
